### ISSUE TITLE
钉钉机器人推送的时间和北京时间差16个小时

### ISSUE THREAD

**Issue by lemoncatting** [Jader/juejin-auto#1]

**Comment by Jader** [comment]
GitHub Action 使用的是 `UTC` 时间，所以北京时间 `02:00` 对应 `UTC` 时间为 `18:00`，如果对时间展示比较纠结，程序中时间组件使用的是 [dayjs](https://dayjs.fenxianglu.cn/category/timezone.html#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E6%97%B6%E5%8C%BA)。欢迎 PR。

**Comment by Jader** [comment]
> _No description provided._

GitHub Action 使用的是 `UTC` 时间，所以北京时间 `02:00` 对应 `UTC` 时间为 `18:00`，如果对时间展示比较纠结，程序中时间组件使用的是 [dayjs](https://dayjs.fenxianglu.cn/category/timezone.html#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E6%97%B6%E5%8C%BA)。欢迎 PR。

**Comment by lemoncatting** [comment]
好滴  已提PR
